name: StackExchange-ES
on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch data
        run: |
          mkdir /tmp/stackexchange
          python bitcoin.stackexchange.com/elasticsearch-scraper/main.py
        env:
            DATA_DIR: /tmp/stackexchange
            CLOUD_ID: ${{ secrets.CLOUD_ID }}
            USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
            USERNAME: ${{ secrets.USERNAME }}
            INDEX: ${{ secrets.INDEX }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            OPENAI_EMBED_MODEL: ${{ secrets.OPENAI_EMBED_MODEL }}
            CHUNK_SIZE: ${{ secrets.CHUNK_SIZE }}
            VECTORSTORE_INDEX: ${{ secrets.VECTORSTORE_INDEX }}
